# Generated by Django 5.1 on 2024-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_face_encoding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='class_name',
            new_name='year',
        ),
    ]
